//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngMap
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIA
    {
        public CATEGORIA()
        {
            this.EVENTO = new HashSet<EVENTO>();
        }
    
        public int ID_CATEGORIA { get; set; }
        public string NOMBRE_CATEGORIA { get; set; }
        public string COLOR_CATEGORIA { get; set; }
        public string DESCRIPCION_CATEGORIA { get; set; }
    
        public virtual ICollection<EVENTO> EVENTO { get; set; }
    }
}
