//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngMap
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTO
    {
        public EVENTO()
        {
            this.GALERIA = new HashSet<GALERIA>();
            this.USUARIO_EVENTO = new HashSet<USUARIO_EVENTO>();
            this.CATEGORIA = new HashSet<CATEGORIA>();
        }
    
        public int ID_EVENTO { get; set; }
        public string NOMBRE_EVENTO { get; set; }
        public string DESCRIPCION_EVENTO { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public string DIRECCION_EVENTO { get; set; }
        public double MAPA_LONGITUD { get; set; }
        public double MAPA_LATITUD { get; set; }
        public decimal COSTO_EVENTO { get; set; }
    
        public virtual ICollection<GALERIA> GALERIA { get; set; }
        public virtual ICollection<USUARIO_EVENTO> USUARIO_EVENTO { get; set; }
        public virtual ICollection<CATEGORIA> CATEGORIA { get; set; }
    }
}
