//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngMap
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities2 : DbContext
    {
        public Database1Entities2()
            : base("name=Database1Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CATEGORIA> CATEGORIA { get; set; }
        public DbSet<EVENTO> EVENTO { get; set; }
        public DbSet<GALERIA> GALERIA { get; set; }
        public DbSet<Location> Location { get; set; }
        public DbSet<USUARIO_EVENTO> USUARIO_EVENTO { get; set; }
        public DbSet<USUARIO_REGISTRADO> USUARIO_REGISTRADO { get; set; }
    }
}
