//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngMap
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_REGISTRADO
    {
        public USUARIO_REGISTRADO()
        {
            this.USUARIO_EVENTO = new HashSet<USUARIO_EVENTO>();
            this.USUARIO_REGISTRADO1 = new HashSet<USUARIO_REGISTRADO>();
            this.USUARIO_REGISTRADO2 = new HashSet<USUARIO_REGISTRADO>();
        }
    
        public int ID_USUARIO { get; set; }
        public string MAIL_USUARIO { get; set; }
        public string PASSWORD { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string APELLIDO_USUARIO { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
    
        public virtual ICollection<USUARIO_EVENTO> USUARIO_EVENTO { get; set; }
        public virtual ICollection<USUARIO_REGISTRADO> USUARIO_REGISTRADO1 { get; set; }
        public virtual ICollection<USUARIO_REGISTRADO> USUARIO_REGISTRADO2 { get; set; }
    }
}
